// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxokejelcejonuigwuvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4b2tlamVsY2Vqb251aWd3dXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTQzMzMsImV4cCI6MjA3Mjc3MDMzM30.7WkeS2stdbHNsXGawZ-lyyk_yM_lKAUoyNhVhqYLDys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});